Repository dresden-elektronik/deconz-rest-plugin, pull requests merged in 2022-10, with the labels that each got.

#6359 Add checks for command ID and MFC to `parseZclAttribute()`
  device_access_fn.cpp
Labels: Fix

#6370 Fix scrypt use of mixed signed/unsigned char*
  crypto/scrypt.cpp
Labels: Fix

#6337 Add support for thermostatic radiator valve from MOES
  product_match.cpp
Labels: Device Request

#6385 Fix: use correct datatype for `config/mountingmode`
  rest_sensors.cpp
  utils/utils.cpp
Labels: Fix

#6386 Add wiki link in DDFs for lumi.plug.mmeu01 and lumi.plug.maeu01
  devices/xiaomi/xiaomi_known_issues_plugfw.md
  devices/xiaomi/xiaomi_sp-euc01_smart_plug.json
  devices/xiaomi/xiaomi_zncz04lm_smart_plug.json
  devices/xiaomi/xiaomi_zncz04lm_smart_plug_v24.json
Labels: Enhancement

#6387 Mark devices as not reachable after repeated APS confirm errors
  device.cpp
Labels: Fix

#6398 Fix delays in rules processing and event propagation
  device_access_fn.cpp
Labels: Fix

#6414 Update th1124zb.json to add item already used on other thermostats
  devices/sinope/th1124zb.json
Labels: Enhancement

#6394 DDF for Aubess Multi Sensor TS0201 _TZ3000_bguser2
  devices/aubess/aubess_muti_sensor_TZ3000_bguser20
Labels: Device Request

#6366 DDF add support for Tuya 1 gang wired Moes ZTS-EUB - 1
  devices/tuya/_TZE200_amp6tsvy_wired_switch_1gang.json
Labels: Device Request

#6405 Create SR-ZG9080A.json
  devices/sunricher/SR-ZG9080A.json
Labels: Device Request

#6402 Remove rescaling of consumption in Develco/friend ZHEMI101 DDF
  devices/develco/zhemi101_external_meter_interface.json
Labels: Fix

#6397 DDF add generic ZHAAlarm sub device json
  devices/generic/constants.json
  devices/generic/subdevices/alarm_sensor.json
Labels: Enhancement

#6395 Add DDF for Zemismart 3A12S-15 led strip controller
  devices/3A-Nue/LXT56-LS27LX1.7.json
Labels: Device Request

#6403 Fix typo for devices of SMaBiT
  devices/smabit/AV201021C_door_sensor.json
Labels: Fix

#6413 Update smt402ad DDF to reflect correct endpoint
  devices/stelpro/smt402ad.json
Labels: Fix

#6404 Create h2l-zbph-rs.json
  devices/philips/h2l-zbph-rs.json
Labels: Device Request

#6334 DDf, add support for doorlock EasyAccess EasyFingerTouch
  devices/easyaccess/easyfingertouch_doorlock.json
  devices/generic/subdevices/door_lock.json
Labels: Device Request

#6373 DDF for Schneider/wiser battery switch FLS/SYSTEM-M/4
  button_maps.json
  devices/wiser/fuga_4button_battery_switch.json
Labels: Device Request

#6433 Fix DDF of Zemismart 3A12S-15 led strip controller
  devices/3A-Nue/LXT56-LS27LX1.7.json
Labels: Fix

#6432 DDF for SONOFF SNZB-02 multi sensor
  devices/sonoff/snzb-02-multisensor
Labels: Device Request

#6434 Fix missing .json extension of Tuya smart plug EU DDF (_TZ3000_typdpbpg)
  devices/tuya/_TZ3000_typdpbpg_smart_plug_eu.json
Labels: Fix

#6400 DDF for Heiman Smart siren HS2WD-E
  devices/heiman/HS2WD-E.json
Labels: Device Request

#6441 DDF for Merten Wiser socket outlet SOCKET/OUTLET/1
  devices/wiser/fuga_socket_outlet.json
Labels: Device Request

#6425 DDF for Sunricher 3-in-1 zigbee push button remote ZG2855-RGB
  button_maps.json
  devices/sunricher/zg2855-rgb_button.json
Labels: Device Request

#6451 Add modelID MOSZB-130 to Develco motion sensor DDF
  devices/develco/moszb-140_motion_sensor.json
Labels: Device Request

#6363 Add DDF for Aqara T1 single rocker switch (no neutral wire) SSM-U02
  devices/xiaomi/xiaomi_ssm-u02_t1_switch.json
Labels: Device Request
