Repository dresden-elektronik/deconz-rest-plugin, pull requests merged in 2022-11, with the labels that each got.

#6506 DDF add support for the Woox R7054 4 buttons
  button_maps.json
  devices/woox/woox_r7054_remote.json
Labels: Device Request

#6488 Add DDFs for Aqara switches QBKG03LM and QBKG04LM
  button_maps.json
  devices/xiaomi/xiaomi_qbkg03lm_switch.json
  devices/xiaomi/xiaomi_qbkg04lm_switch.json
Labels: Device Request

#6502 Use simpler and more robust endpoint match expression for Xiaomi smart plugs
  devices/xiaomi/xiaomi_sp-euc01_smart_plug.json
  devices/xiaomi/xiaomi_zncz04lm_smart_plug.json
  devices/xiaomi/xiaomi_zncz04lm_smart_plug_v24.json
Labels: Fix

#6489 Fix DDF for Heiman Smart siren HS2WD-E, modifiying swversion attribute
  devices/heiman/HS2WD-E.json
Labels: Fix

#6487 Fix too frequent database writes
  database.cpp
  device_compat.cpp
  utils/utils.cpp
  utils/utils.h
Labels: Fix

#6481 DDF, add support for Woox R7052 Smart SOS Button
  devices/woox/woox_r7052_ts0215a.json
Labels: Device Request

#6513 Add Innr SP-234 based on sp120
  devices/innr/sp_234.json
Labels: Device Request

#6514 Improve scheduling of APS requests
  de_web_plugin.cpp
  de_web_plugin_private.h
  device.cpp
  device_access_fn.cpp
  device_access_fn.h
  device_tick.cpp
  state_change.cpp
  state_change.h
Labels: Enhancement

#6519 Improve Device polling and group task scheduling
  de_web_plugin.cpp
  device.cpp
Labels: Enhancement

#6518 Replace Qt Javascript engine with Duktape JS
  de_web.pro
  device_access_fn.cpp
  device_descriptions.cpp
  device_js/device_js.cpp
  device_js/device_js.h
  device_js/device_js_duktape.cpp
  device_js/device_js_duktape.h
  device_js/device_js_wrappers.cpp
  device_js/device_js_wrappers.h
  device_js/duk_config.h
  device_js/duktape.c
  device_js/duktape.h
  devices/centralite/motion_sensor-a.json
  devices/generic/illuminance_cluster/lux_to_lightlevel.js
  devices/tuya/tuya_swversion.js
  devices/xiaomi/xiaomi_battery.js
  devices/xiaomi/xiaomi_rtcgq14lm_lux_to_lightlevel.js
  devices/xiaomi/xiaomi_swversion.js
Labels: Enhancement

#6520 Fix state/colormode default DDF item
  devices/generic/items/state_colormode_item.json
Labels: Fix

#6521 DDF for Phoscon Hive
  devices/dresden_elektronik/hive.json
Labels: Device Request

#6503 FIX/DDF add support by DDF for the Aqara Single Switch Module T1
  devices/xiaomi/xiaomi_lumi.switch.n0agl1_switch.json
Labels: Device Request
