Repository dresden-elektronik/deconz-rest-plugin, pull requests merged in 2023-03, with the labels that each got.

#6770 Adjusting swversion to a whole day refresh
  devices/generic/items/attr_swversion_item.json
Labels: Fix

#6768 DDF for Third Reality Smart Plug Gen2
  devices/third_reality/3RSP02028BZ_smart_plug.json
Labels: Device Request

#6764 DDf, add support for TMZ-02 Mini a.k.a Tmz02L-16A-W
  devices/tuya/_TZ3000_txpirhfq_1gang_module.json
Labels: Device Request

#6763 Add DDF for UseeLink Powerbar SM-SO306-U ( _TZ3000_cfnprab5)
  devices/tuya/_TZ3000_TS011F_PowerStrip.json
Labels: Device Request

#6752 Add DDF for some 2.4GHz mmWave radar
  devices/tuya/_TZE200_TS0601_mmWave_Radar.json
Labels: Device Request

#6736 Add DDF for Tuya Photoelectric Smoke Detector _TZE200_m9skfctm
  devices/tuya/_TZE200_m9skfctm_smoke_detector.json
Labels: Device Request

#6735 Update DDF to add support for MOES _TZ3000_itnrsufe
  devices/moes/Moes_TZ3000_TS0201_temp_hum_with_LCD.json
Labels: Device Request

#6776 IKEA Vindstyrka
  device_access_fn.cpp
  devices/ikea/vindstyrka_air_quality_sensor.json
  general.xml
Labels: Device Request

#6774 [FIX] Update and rename _TZ3000_ygvf9xzp_4gang_remote.json to _TZ3000_TS044…
  devices/tuya/_TZ3000_TS044_4gang_remote.json
Labels: Fix

#6729 DDF for LIDL Smart watering timer (_TZE200_htnnfasr)
  devices/tuya/_TZE200_htnnfasr_water_valve
Labels: Device Request

#6777 Hue gamut-A ZLL lights
  devices/generic/items/cap_color_gamut_type_item.json
  devices/philips/fc03_state.js
  devices/philips/light_zll_A.json
  devices/philips/light_zll_B.json
  rest_lights.cpp
Labels: Fix

#6718 Update DDF for battery bindings for Aubess/Tuya temperature and humidity sensors
  devices/aubess/aubess_multi_sensor_TZ3000_bguser20.json
  devices/aubess/aubess_muti_sensor_TZ3000_bguser20.json
  devices/tuya/_TZ3000_yd2e749y_temp_hum_sensor.json
Labels: Enhancement

#6732 Update and rename ledsenk08_door_vibration_sensor.json to ldsenk08_do…
  devices/adeo/ldsenk08_door_vibration_sensor.json
Labels: Enhancement

#6782 Fix battery drain TZ3000 TS0042 2-gang remote
  button_maps.json
  devices/tuya/_TZ3000_TS0042_2gang_remote.json
  devices/tuya/_TZ3000_t8hzpgnd_2gang_bat_switch.json
Labels: Fix

#6783 Fix TS0043_3gang_remote
  devices/tuya/TS0043_3gang_remote.json
Labels: Fix

#6794 Fix DDF _TZ3000_au1rjicn manufacturer name typo
  devices/tuya/_TZ3000_n2egfsli_door_sensor.json
Labels: Fix

#6795 Force DDF supported presence sensors to state false during start
  device_ddf_init.cpp
Labels: Fix

#6797 Fix Dresden Elektronik Scene Switch long press button events
  button_maps.json
Labels: Fix

#6802 Fixed missing file extension for Parkside water valve DDF
  devices/tuya/_TZE200_htnnfasr_water_valve.json
Labels: Fix

#6799 add .devcontainer to .gitignore and add some missing fn params
  .gitignore
  devices/ikea/kadrilj_blind.json
  devices/xiaomi/xiaomi_airmonitor_acn01.json
  devices/xiaomi/xiaomi_rtcgq14lm_p1_presence_sensor.json
  devices/xiaomi/xiaomi_wrs-r02_h1_switch.json
Labels: Fix

#6760 DDF, improve support for Xiaomi Aqara relay controller lumi.relay.c2acn01
  devices/xiaomi/xiaomi_lumi.relay.c2acn01.json
Labels: Fix

#6803 IKEA SYMFONISK sound remote gen2
  button_maps.json
  button_maps.schema.json
  devices/ikea/symfonisk_sound_remote_gen2.json
Labels: Device Request

#6824 Bug fix: support for SYMFONISK controller broken.
  button_maps.json
Labels: Fix

#6809 Update fyrtur_block-out_roller_blind.json
  devices/ikea/fyrtur_block-out_roller_blind.json
Labels: Fix

#6813 Fix ubisys J1 auto calibration
  devices/generic/items/config_windowcoveringtype_item.json
  devices/ubisys/j1_5502.json
  devices/ubisys/j1r_5602.json
  general.xml
  window_covering.cpp
Labels: Fix

#6820 Update hive.json attr/powerup instead of config/powerup
  devices/dresden_elektronik/hive.json
Labels: Fix

#6825 Remove unused _TZE200_htnnfasr_water_valve file
  devices/tuya/_TZE200_htnnfasr_water_valve
Labels: Enhancement

#6836 Fix Qt5 skip empty parts deprecated warning
  database.cpp
  de_web_plugin.cpp
  device_access_fn.cpp
  group.cpp
  rest_rules.cpp
  rest_schedules.cpp
  rest_sensors.cpp
  rule.cpp
  thermostat.cpp
  tuya.cpp
Labels: Fix

#6837 Fix potential SEGV in debug print
  read_files.cpp
Labels: Fix
