Repository dresden-elektronik/deconz-rest-plugin, pull requests merged in 2023-12, with the labels that each got.

#7409 Update lxn59-1s7lx1.0 Smart plug DDF to Gold
  devices/3A-Nue/lxn59-1s7lx1.0.json
Labels: Enhancement

#7406 DDF to support Namron S903TH-ZG multisensor
  devices/namron/4512765_hum_temp.json
Labels: Device Request

#7412 Update cap measured generic file names
  devices/generic/items/cap_measured_value_max_item.json
  devices/generic/items/cap_measured_value_min_item.json
  devices/generic/items/cap_measured_value_quantity_item.json
  devices/generic/items/cap_measured_value_substance_item.json
  devices/generic/items/cap_measured_value_unit_item.json
Labels: Fix

#7446 Speed up first time loading of DDF for former legacy lights
  de_web_plugin.cpp
  device.cpp
Labels: Enhancement

#7440 Use constants for xiaomi_jtqj-bf-01lm_gas_leak_detector.json
  devices/xiaomi/xiaomi_jtqj-bf-01lm_gas_leak_detector.json
Labels: Enhancement

#7427 Use constants for 3RWS18BZ_water_sensor.json
  devices/third_reality/3RWS18BZ_water_sensor.json
Labels: Enhancement

#7429 Use constants for _TZ3000_bmfw9ykl_vibration_sensor.json
  devices/tuya/_TZ3000_bmfw9ykl_vibration_sensor.json
Labels: Enhancement

#7435 Use constants for smszb-120_smoke_detector.json
  devices/develco/smszb-120_smoke_detector.json
Labels: Enhancement

#7428 Use constants for bwa-1_water_sensor.json
  devices/bosch/bwa-1_water_sensor.json
Labels: Enhancement

#7430 Fix path of tuya_swversion.js for Woox_R7049_Smart_Smoke_Alarm.json
  devices/woox/Woox_R7049_Smart_Smoke_Alarm.json
Labels: Fix

#7431 Fix path of tuya_swversion.js for bw_is4_multisensor.json
  devices/blitzwolf/bw_is4_multisensor.json
Labels: Fix

#7432 Fix path of tuya_swversion.js for zb003-x_multi_sensor.json
  devices/fantem/zb003-x_multi_sensor.json
Labels: Fix

#7437 Fix path of xiaomi_firmware.js for xiaomi_sp-euc01_smart_plug.json
  devices/xiaomi/xiaomi_sp-euc01_smart_plug.json
Labels: Fix

#7439 Fix path for xiaomi_firmware.js for xiaomi_zncz12lm_smart_plug.json
  devices/xiaomi/xiaomi_zncz12lm_smart_plug.json
Labels: Fix

#7422 Add the SNZB-02P variant of the sensor to the DDF
  devices/sonoff/snzb-02-multisensor.json
Labels: Device Request

#7444 DDF for Sonoff/zbeacon DS01 open/close sensor
  devices/sonoff/snzb-04_open_close_sensor.json
Labels: Device Request

#7447 DDF add variant of Tuya Smart Button IH-663 (_TZ3000_fa9mlvja)
  button_maps.json
  devices/tuya/_TZ3000_TS0041_1gang_bat.json
Labels: Device Request

#7426 Fix naming convention for generic files
  devices/generic/items/cap_color_gradient_styles_item.json
  devices/generic/items/state_current_p1_item.json
  devices/generic/items/state_current_p2_item.json
  devices/generic/items/state_current_p3_item.json
  devices/generic/subdevices/air_purifier.json
  devices/generic/subdevices/air_quality_sensor.json
  devices/generic/subdevices/light_level_sensor.json
  devices/generic/subdevices/on_off_light.json
  devices/generic/subdevices/on_off_output.json
  devices/generic/subdevices/on_off_plugin_unit.json
  devices/generic/subdevices/open_close_sensor.json
  devices/generic/subdevices/water_leak_sensor.json
Labels: Enhancement

#7442 Remove duplicate device identifier for _TZ3000_TS0207_water_leak_sens…
  devices/tuya/_TZ3000_TS0207_water_leak_sensor.json
Labels: Fix

#7443 Remove duplicate device identifier for _TZ3000_TS011F_PowerStrip.json
  devices/tuya/_TZ3000_TS011F_PowerStrip.json
Labels: Fix

#7402 DDF add variant of Tuya presence sensor (_TZ3000_lf56vpxj)
  devices/tuya/ts0202_presence_sensor.json
Labels: Device Request

#7410 C++ Add support for set Level for Legrand covering
  rest_lights.cpp
Labels: Enhancement

#7337 DDF for TRÅDFRI LED bulb E14 250lm warm white clear chandelier
  devices/ikea/tradfri_bulb_e14_ww_clear_250lm.json
Labels: Device Request

#7445 DDF for Ikea Parasoll open/close sensor
  devices/ikea/parasoll_open_close_sensor.json
Labels: Device Request

#7267 Add `config/bri/couple_ct` to Hue lights that support it.
  devices/philips/light_zb3_C.json
  devices/philips/light_zb3_C_festavia.json
  devices/philips/light_zb3_C_gradient.json
  devices/philips/light_zb3_white_ambiance.json
Labels: Feature Request, Device Improvement

#7268 Add `config/bri/couple_ct` to IKEA lights that support it.
  devices/ikea/tradfri_bulb_cws_A.json
  devices/ikea/tradfri_bulb_e27_ws_opal_980lm.json
Labels: Feature Request, Device Improvement

#6175 Add further Danfoss specific resource items
  devices/danfoss/etrv0100_thermostat.json
  devices/generic/items/config_lastchange_amount_item.json
  devices/generic/items/config_lastchange_source_item.json
  devices/generic/items/config_lastchange_time_item.json
  devices/generic/items/config_loadbalancing_item.json
  devices/generic/items/config_radiatorcovered_item.json
  devices/generic/items/config_windowopendetectionenabled_item.json
  resource.cpp
  resource.h
  rest_sensors.cpp
Labels: API Extension

#7297 Bug fix IKEA VINDSTYRKA: Translate VOC index to tVOC level.
  devices/ikea/fc7e_tvoc_level.js
  devices/ikea/vindstyrka_air_quality_sensor.json
Labels: Device Improvement, Fix

#7310 Add DDF for MHCOZY ZG-005-RF
  devices/mhcozy/ts0004.json
Labels: Device Request, Device Improvement

#7460 DDF optimizations for Danfoss Ally
  devices/danfoss/danfoss_errorcode.js
  devices/danfoss/etrv0100_thermostat.json
Labels: Device Improvement

#7421 DDF for ubisys H1 thermostat
  devices/ubisys/h1.json
  general.xml
Labels: Device Request

#7452 DDF support "cmd": "any" wildcard
  device_access_fn.cpp
  zcl/zcl.h
Labels: Enhancement

#7461 Fix generated scene names
  de_web_plugin.cpp
Labels: Fix

#7462 Make sensors attr/mode a ResourceItem
  devices/generic/items/attr_mode_item.json
  resource.cpp
  resource.h
  rest_sensors.cpp
  sensor.cpp
  sensor.h
Labels: Enhancement

#7408 DDF for Philips Hue White Ambiance E27 Edison ST64 Filament 550lm
  devices/philips/light_zb3_white_ambiance.json
Labels: Device Request

#7465 DDF for Greeble JZ-RGBW-Z01 light
  devices/greeble/jz-rgbw-z01.json
Labels: Device Request

#7466 Fix a problem for the Legrand Wireless Scenes command
  devices/legrand/wireless_scenes_command.json
Labels: Fix

#7204 DDF for Tuya bidirectional energy meter (_TZE204_ac0fhfiq)
  device_access_fn.cpp
  devices/tuya/_TZE204_ac0fhfiq_energy_meter.json
Labels: Device Request, API Extension

#7468 Use correct type for ubisys S1/S1-R
  devices/ubisys/s1_5501_s1r_5601.json
Labels: Device Improvement

#7471 DDF for Popp Smart Thermostat
  devices/danfoss/etrv0100_thermostat.json
Labels: Device Request

#7474 DDF for Hive Radiator Valve
  devices/danfoss/etrv0100_thermostat.json
Labels: Device Request

#7475 DDF internal optimizations for Danfoss Ally and derivatives
  devices/danfoss/danfoss_windowopen_state.js
  devices/danfoss/etrv0100_thermostat.json
Labels: Enhancement

#7495 Forward device has DDF info to core for UI
  device.cpp
Labels: Enhancement

#7486 DDF for innr SP 240
  devices/innr/sp_240.json
Labels: Device Request

#7488 DDF add support for WOOLLEY/eWeLink SmartPlug CK-BL702-SWP-01(7020)
  devices/sonoff/ck-bl702-swp-01(7020)_plug.json
Labels: Device Request

#7493 Fix `config/mode` for ubisys devices S1/S2(-R)/J1(-R)
  CMakeLists.txt
  de_web.pro
  de_web_plugin_private.h
  device_setup.cpp
  devices/ubisys/j1_5502.json
  devices/ubisys/j1r_5602.json
  devices/ubisys/s1_5501_s1r_5601.json
  devices/ubisys/s2_5502.json
  devices/ubisys/s2r_5602.json
  rest_sensors.cpp
Labels: Fix

#7472 Remove deprecated Danfoss code
  CMakeLists.txt
  bindings.cpp
  database.cpp
  de_web.pro
  de_web_plugin.cpp
  de_web_plugin_private.h
  diagnostics.cpp
  rest_sensors.cpp
  thermostat.cpp
  thermostat.h
  thermostat_ui_configuration.cpp
  thermostat_ui_configuration.h
Labels: Enhancement

#7497 Force classic join/re-join for devices
  zdp/zdp_handlers.cpp
Labels: Fix

#7467 Add resource item for external temp measurement for Bosch Thermostat II
  devices/bosch/thermostat2.json
  general.xml
Labels: Enhancement

#7503 Fix button handlers for dresden elektronik Scene Switch
  devices/dresden_elektronik/scene_switch.json
  devices/dresden_elektronik/scene_switch_bri.js
  devices/dresden_elektronik/scene_switch_on.js
  devices/dresden_elektronik/scene_switch_scenes.js
Labels: Fix

#7504 DDF for Bosch room thermostat II (BTH-RM)
  devices/bosch/room_thermostat2.json
Labels: Device Request

#7506 DDF for Develco/frient temperature/humidity sensor HMSZB-120
  bindings.cpp
  devices/develco/hmszb_temp_hum_sensor.json
  devices/frient/hmszb_temp_hum_sensor.json
Labels: Device Request

#7505 DDF for Heiman Keyfobs HS1RC/HS1RC-M//HS1RC-E
  devices/heiman/hs1rc_keyfob.json
Labels: Device Request

#7483 DDF for Sonoff SNZB-01P
  button_maps.json
  devices/sonoff/snzb-01p_switch_wireless.json
Labels: Device Request

#7487 DDF for Zemismart 1-gang Remote (_TZ3000_tk3s5tyg)
  button_maps.json
  devices/tuya/_TZ3000_TS0041_1gang_bat.json
Labels: Device Request

#7420 DDF for IKEA Ormanas led strip
  devices/ikea/ormanas_led_strip.json
Labels: Device Request
