Repository dresden-elektronik/deconz-rest-plugin, pull requests merged in 2023-06, with the labels that each got.

#6913 Refactor MMO hash function
  crypto/mmohash.cpp
  crypto/mmohash.h
  de_web.pro
  rest_devices.cpp
  utils/utils.cpp
  utils/utils.h
Labels: Enhancement

#6919 Xiaomi special attribute in DDF
  devices/generic/constants.json
  devices/generic/items/attr_xiaomi_item.json
  devices/generic/items/config_battery_bis_item.json
  devices/generic/items/config_devicemode_bis_item.json
  devices/generic/items/config_reportgrid_item.json
  devices/generic/items/config_sensitivity_bis_item.json
  devices/generic/items/config_triggerdistance_bis_item.json
  devices/generic/items/state_airquality_bis_item.json
  devices/generic/items/state_airqualityppb_bis_item.json
  devices/generic/items/state_humidity_bis_item.json
  devices/generic/items/state_open_bis_item.json
  devices/generic/items/state_orientation_item.json
  devices/generic/items/state_orientation_x_item.json
  devices/generic/items/state_orientation_y_item.json
  devices/generic/items/state_orientation_z_item.json
  devices/generic/items/state_pressure_bis_item.json
  devices/generic/items/state_temperature_bis_item.json
  devices/generic/items/state_water_bis_item.json
  devices/xiaomi/0001_battery.js
  devices/xiaomi/0101_orientation.js
  devices/xiaomi/aq1_vibration_sensor.json
  devices/xiaomi/aq1_vibration_sensor_orientation.js
  devices/xiaomi/fcc0_airmonitor_acn01.js
  devices/xiaomi/lumi_airmonitor_acn01.json
  devices/xiaomi/lumi_curtain.json
  devices/xiaomi/lumi_curtain_acn002.json
  devices/xiaomi/lumi_motion_ac01.json
  devices/xiaomi/lumi_sensor_magnet_aq2.json
  devices/xiaomi/lumi_sensor_wleak_aq1.json
  devices/xiaomi/lumi_vibration_aq1.json
  devices/xiaomi/lumi_weather.json
  devices/xiaomi/xiaomi_battery.js
  devices/xiaomi/xiaomi_mccgq11lm_openclose_sensor.json
  resource.cpp
  resource.h
  rest_sensors.cpp
Labels: Device Improvement, Fix

#7017 Add DDF for Tradfri bulb e14 ws candle opal 470lm
  devices/ikea/tradfribulbe14wscandleopal470lm.json
Labels: Device Request

#7018 Add DDF for Ikea Tradfri Control Outlet
  devices/ikea/tradfri_control_outlet.json
Labels: Device Request

#7027 DDF, add support for LDS battery switch
  button_maps.json
  devices/lds/ZBT-DIMSwitch-D0000_remote.json
Labels: Device Request

#7022 DDF Add support for SM0201/LH-331ZB multi sensor
  devices/_TYZB01_SM0201_temp_hum_sensor.json
Labels: Device Request

#7021 DDF Rename _TZ3000_yd2e749y_temp_hum_sensor.json
  devices/tuya/_TZ3000_TS0201_temp_hum_sensor.json
Labels: Enhancement

#7041 Support building without OpenSSL
  crypto/mmohash.cpp
Labels: Enhancement

#7049 Fix deprecated and other warnings
  backup.cpp
  bindings.cpp
  change_channel.cpp
  de_web_plugin.cpp
  green_power.cpp
  permitJoin.cpp
  reset_device.cpp
  rest_configuration.cpp
  rest_sensors.cpp
  utils/utils.h
Labels: Fix

#7054 Add ZHABattery sensor Danalock V3
  devices/danalock/danalock_v3.json
Labels: Enhancement

#7053 CMake build system support
  .gitignore
  BUILDING.md
  CMakeLists.txt
  README.md
  crypto/random.cpp
  sensor.h
  sqlite3/CMakeLists.txt
Labels: Enhancement

#6989 Add DDF validator action
  .github/workflows/verify-ddf-json.yml
Labels: Enhancement
