Repository dresden-elektronik/deconz-rest-plugin, pull requests merged in 2023-07, with the labels that each got.

#7074 Fix Tuya SM0201 config.battery refresh.interval
  devices/_TYZB01_SM0201_temp_hum_sensor.json
Labels: Fix

#7075 Fix Xiaomi tunable white bulb (aqcn02) use cap/color/ct/[min | max]
  devices/xiaomi/xiaomi_lumi.light.aqcn02_TunableWhite_Bulb.json
Labels: Fix

#7076 Fix ubisys LD6 use cap/color/ct/[min | max]
  devices/ubisys/ld6.json
Labels: Fix

#7078 DDF set state to "Gold" from "Silver" for the Tuya Soil Sensor _TZE200_myd45weu
  devices/tuya/_TZE200_myd45weu_soil_sensor.json
Labels: Enhancement

#7077 Fix Sengled E12-N1E use cap/color/ct/[min | max]
  devices/sengled/E12-N1E.json
Labels: Fix

#7079 Fix Tint GU10 spot use cap/color/*
  devices/mli/tint_gu10_spot_zbt-colortemperature.json
Labels: Fix

#7081 Fix ubisys LD6 use cap/color/*
  devices/ubisys/ld6.json
Labels: Fix

#7082 Fix dresden elektronik FLS-PP lp use cap/color/*
  devices/dresden_elektronik/fls_pp3.json
Labels: Fix

#7083 Fix Zigfred Uno use cap/color/* and poll intervals
  devices/siglis/zigfred_uno_wired_switch.json
Labels: Fix

#7084 Fix Linkind ZBT-CCTLight-M3500107 use cap/color/* and fix poll interval
  devices/linkind/ZBT-CCTLight-M3500107.json
Labels: Fix

#7085 Fix Linkind ZBT-CCTLight-D0106 use cap/color/* and fix poll interval
  devices/linkind/ZBT-CCTLight-D0106.json
Labels: Fix

#7086 Fix Ikea E27 CWS Opal 600lm use cap/color/* and code cleanup
  devices/ikea/e27_cws_opal_600lm_light.json
Labels: Fix

#7089 Fix DDF validation errors for samjin_multi_sensor.json
  devices/samsung/samjin_multi_sensor.json
Labels: Device Improvement

#7095 Fix Sengled E12-N1 use cap/color/*
  devices/sengled/E12-N1E.json
Labels: Fix

#7096 Fix Zigfred Plus use cap/color/*
  devices/siglis/zigfred_plus_wired_switch.json
Labels: Fix

#7097 Fix Aubess multi sensor config/battery parse function
  devices/aubess/aubess_multi_sensor_TZ3000_bguser20.json
Labels: Fix

#7062 Fix missing battery resource item for Bosch thermostat II
  devices/bosch/thermostat2.json
Labels: Device Improvement

#7099 Fix rand() deprecated warnings
  light_node.cpp
  rest_schedules.cpp
  rest_touchlink.cpp
Labels: Fix

#7100 CMake support locating OpenSSL
  CMakeLists.txt
  crypto/scrypt.cpp
Labels: Enhancement

#7101 Fix QByteArray::replace() deprecated warnings
  upnp.cpp
Labels: Fix

#7112 DEV handle Mgmt_Bind_rsp NOT_PERMITTED status
  device.cpp
Labels: Fix

#7116 Fix Bosch thermostat RBSH-TRV0-ZB-EU battery refresh interval
  devices/bosch/thermostat2.json
Labels: Fix

#7093 DDF for Hue Zigbee-3 White lights
  devices/philips/light_zb3_white.json
Labels: Device Request

#7065 Add DDF support for Philips Hue Ensis black edition and Philips Hue Luster White and Color Ambiance within the light_zb3_C.json
  devices/philips/light_zb3_C.json
Labels: Device Request

#7044 DDF Update for the Owon THS317-ET
  devices/owon/THS317-ET_temperature_sensor.json
Labels: Enhancement

#7052 DDF add support for TZ3000_air9m6af and _TZ3000_bppxj3sf from LELLKI
  devices/tuya/_TZ3000_TS011F_PowerStrip.json
Labels: Device Request

#7090 Bug fix: fp1 triggerdistance not updated from special atttribute
  devices/xiaomi/lumi_motion_ac01.json
Labels: Device Improvement, Fix

#7028 DDF for Osram CLA60 TW OSRAM
  devices/osram/cla60_tw.json
Labels: Device Request

#7030 DDF for Osram Classic A60 RGBW
  devices/osram/classic_a60_rgbw.json
Labels: Device Request

#7032 DDF for Osram Classic B40 TW
  devices/osram/classic_b40_tw.json
Labels: Device Request

#7034 DDF for Eva Powermeter
  devices/eva/powermeter.json
Labels: Device Request

#7098 Add dynamic ResourceItemDescriptors
  device_descriptions.cpp
  resource.cpp
  resource.h
  utils/utils.h
Labels: Enhancement

#7023 Update DDF for H2L-ZBPH-RS roller shutter
  devices/home2link/H2L-ZBPH-RS.json
Labels: Device Request

#7092 Hue ZB3 white ambiance lights
  devices/philips/light_zb3_white_ambiance.json
Labels: Device Request

#7087 DDF Add support for Paulmann Zigbee Switch 501.34
  button_maps.json
  devices/paulmann/501_34_battery_switch.json
Labels: Device Request

#7091 Bug fix: false water detection for lumi_sensor_wleak_aq1
  devices/xiaomi/lumi_sensor_wleak_aq1.json
Labels: Device Improvement

#7118 Add Attr.index to Javascript engine
  device_access_fn.cpp
  device_js/device_js.h
  device_js/device_js_duktape.cpp
Labels: Enhancement

#7122 Move _TYZB01_SM0201_temp_hum_sensor.json to devices/tuya
  devices/tuya/_TYZB01_SM0201_temp_hum_sensor.json
Labels: Enhancement

#7126 Add macOS build script (Intel / x86_64)
  BUILDING.md
  build-macos.sh
Labels: Enhancement

#7117 Support setting ZCL frame control (optional) in "zcl:cmd"
  device_access_fn.cpp
  device_ddf_init.cpp
  zcl/zcl.cpp
  zcl/zcl.h
Labels: Enhancement

#7024 Delete h2l-zbph-rs.json
  devices/philips/h2l-zbph-rs.json
Labels: Enhancement

#7051 DDF add support for _TZE204_sxm7l9xa mmWave radar sensor
  devices/tuya/_TZE204_sxm7l9xa_mmwave_radar.json
Labels: Device Request

#6990 DDF add support for the Adeo LDSENK09 Key FOB 4 buttons
  button_maps.json
  de_web_plugin.cpp
  devices/adeo/ldsenk09_keyfob.json
Labels: Device Request

#7119 Add generic measured_value items
  devices/generic/items/cap_measured_value_max.json
  devices/generic/items/cap_measured_value_min.json
  devices/generic/items/cap_measured_value_unit.json
  devices/generic/items/state_measured_value_item.json
Labels: Enhancement

#7129 Fix unsafe sprintf warning, replace with snprintf (xmas strip)
  xmas.cpp
Labels: Fix

#7128 Refactor gateway password code
  CMakeLists.txt
  authorisation.cpp
  crypto/password.cpp
  crypto/password.h
  database.cpp
  de_web.pro
  de_web_plugin_private.h
  rest_configuration.cpp
Labels: Enhancement

#7121 DDF update the Tuya air quality sensor _TZE200_dwcarsat with "state/measured_value"
  devices/generic/constants.json
  devices/generic/subdevices/carbondioxide_sensor.json
  devices/generic/subdevices/formaldehyde_sensor.json
  devices/generic/subdevices/particulatematter_sensor.json
  devices/tuya/_TZE200_dwcarsat_air_sensor.json
Labels: Device Request

#7133 DDF for OWON AC201 thermostat
  bindings.cpp
  database.cpp
  de_web_plugin.cpp
  devices/owon/ac201.json
  fan_control.cpp
  thermostat.cpp
Labels: Device Request

#7132 Enable changing trigger distance of Tuya presence sensor (_TZE204_sxm7l9xa)
  devices/tuya/_TZE204_sxm7l9xa_mmwave_radar.json
Labels: Enhancement

#7110 DDF for Loratape 3-gang remote (_TZ3000_yw5tvzsk)
  button_maps.json
  devices/tuya/_TZ3000_TS0043_3gang_remote.json
Labels: Device Request
