Repository dresden-elektronik/deconz-rest-plugin, pull requests merged in 2023-08, with the labels that each got.

#7140 Cleanup debug prints and remove addr.toStringExt() usage
  bindings.cpp
  de_web_plugin.cpp
  de_web_widget.cpp
  reset_device.cpp
  rest_lights.cpp
  rest_touchlink.cpp
  window_covering.cpp
  zdp/zdp_handlers.cpp
Labels: Enhancement

#7142 Remove support loading old MAC address format of lights
  database.cpp
Labels: Enhancement

#7148 DDF for Tuya 4-gang switch (_TZ3000_pkeqinnt)
  button_maps.json
  devices/tuya/_TZ3000_TS0043_3gang_remote.json
Labels: Device Request

#7143 Remove FLS-NB, ubisys C++ code and rule "BIND" support
  bindings.cpp
  de_web_plugin.cpp
  de_web_plugin_private.h
  electrical_measurement.cpp
  occupancy_sensing.cpp
  rest_lights.cpp
  rest_rules.cpp
  rest_sensors.cpp
  rule.cpp
  rule.h
Labels: Enhancement

#7141 Remove connectivity REST-API endpoint
  CMakeLists.txt
  connectivity.cpp
  connectivity.h
  de_web.pro
  de_web_plugin_private.h
  rest_lights.cpp
Labels: Enhancement

#7152 Cleanup backup.cpp include dependencies
  backup.cpp
Labels: Enhancement

#7153 DDF for ubisys S1-R (5601)
  devices/ubisys/s1_5501_s1r_5601.json
Labels: Device Request

#7154 DDF for ubisys D1-R (5603)
  devices/ubisys/d1_5503_d1r_5603.json
Labels: Device Request

#7156 Add Develco specific LED indication attribute to basic cluster
  general.xml
Labels: Enhancement

#7158 Prepare for deconz-lib deCONZ::Attribute::lastRead() change
  de_web_plugin.cpp
  poll_manager.cpp
Labels: Enhancement

#7159 DDF for Tuya temperature / humidity sensor (_TZ3000_0s1izerx) (#7113)
  devices/tuya/_TZ3000_TS0201_temp_hum_sensor.json
Labels: Device Request

#7189 Add support for frient SPLZB-141 smart plug
  devices/frient/splzb-131_smart_plug.json
Labels: Device Request

#7192 DDF add support for lxn59-2s7lX1.0
  devices/3A-Nue/Lxn59-2s7lX1.0.json
Labels: Device Request

#7164 [subdevice] Add ZHATime type
  devices/danfoss/etrv0100_thermostat.json
  devices/generic/constants.json
  devices/generic/subdevices/time.json
Labels: Enhancement

#7166 [subdevice] Add type Level control switch
  devices/generic/constants.json
  devices/generic/subdevices/level_control_switch.json
  devices/legrand/cable_outlet.json
Labels: Enhancement

#7169 [subdevice] items_optional for ZHAAlarm
  devices/generic/subdevices/alarm_sensor.json
  devices/heiman/hs2wd-e_smart_siren.json
  devices/lixee/zlinky_tic_histo_tri_hphc.json
  devices/lixee/zlinky_tic_historique_mono_base.json
  devices/lixee/zlinky_tic_historique_mono_hphc.json
  devices/lixee/zlinky_tic_standard_mono_base.json
  devices/lixee/zlinky_tic_standard_tri_hphc.json
Labels: Enhancement

#7177 [subdevice] items_optional for $TYPE_ON_OFF_LIGHT
  devices/generic/subdevices/onoff_light.json
Labels: Enhancement

#7179 [subdevice] items_optional for ZHAPower
  devices/generic/subdevices/power_sensor.json
Labels: Enhancement

#7195 DDF for further NEO NAS-WR01B smart plugs (_TZ3000_waho4jtj)
  devices/neo/NAS-WR01B_TS011F.json
Labels: Device Request

#7175 Fix some indent
  devices/generic/subdevices/range_extender.json
  devices/generic/subdevices/window_covering_device.json
  devices/ouellet/OTH4000-ZB.json
  devices/tuya/_TZE200_htnnfasr_water_valve.json
Labels: Fix

#7196 DDF add support for ROVF (TMZ02L-16A-B2) Mini Switch
  devices/tuya/_TZ3000_hkkkuk7k_mini_switch.json
Labels: Device Request

#7199 DDF for Ikea RODRET Remote Control
  button_maps.json
  devices/ikea/rodret_remote_control.json
Labels: Device Request

#7188 Fix ZCLDB wrong « Neutral current » attribute number
  general.xml
Labels: Fix

#7203 Fix battery not reported for Tuya 4-gang remote _TZ3000_TS0044_4gang_remote.json
  devices/tuya/_TZ3000_TS0044_4gang_remote.json
Labels: Fix
