Repository dresden-elektronik/deconz-rest-plugin, pull requests merged in 2024-05, with the labels that each got.

#7735 Fix pairing Profalux roller shutter in legacy code
  de_web_plugin.cpp
Labels: Fix

#7736 Remove unused Ikea blind DDF's
  devices/ikea/fyrtur_block-out_roller_blind.json
  devices/ikea/kadrilj_blind.json
  devices/ikea/tredansen_block-out_cellul_blind.json
Labels: Fix

#7749 Remove referer filter on deletePassword endpoint
  rest_configuration.cpp
Labels: Enhancement

#7745 Update API responses for time config
  rest_configuration.cpp
Labels: Fix

#7753 DDF add tuya clone for Soil sensor
  devices/tuya/_TZE200_myd45weu_soil_sensor.json
Labels: Device Request

#7751 Fix introspect response
  rest_devices.cpp
Labels: Fix

#7726 Fix script paths for DDF files
  devices/moes/Moes_MS-105-M_1_gang_dimmer_module.json
  devices/moes/Moes_ZM-105-M_1_gang_dimmer.json
  devices/sunricher/SR-ZG9030A-MW.json
Labels: Fix

#7718 Normalized names for Tuya remotes and added variant for TZ3000_TS0041
  button_maps.json
  devices/tuya/_TZ3000_TS0041_1gang_remote.json
  devices/tuya/_TZ3000_TS0042_2gang_remote.json
  devices/tuya/_TZ3000_TS0043_3gang_remote.json
  devices/tuya/_TZ3000_TS0044_4gang_remote.json
Labels: Device Request

#7699 DDF for Yagusmart Zigbee Smart Wall Light Switch 1 Gang No Neutral Wire Required
  devices/tuya/_TYZB01_TS0011_1gang_wired_no_neutral.json
Labels: Device Request

#7657 DDF for Tapestry Presence Z1
  devices/tapestry/tapestry_presence_z1.json
Labels: Device Request

#7757 Fix Ikea Rodret group bindings/button events
  devices/ikea/rodret_dimmer.json
Labels: Fix

#7743 Add workflow for DDF Bundles
  .github/workflows/ci-ddf-store.yml
  .github/workflows/verify-ddf-json.yml
Labels: Enhancement

#7750 Support for DDF bundles
  CMakeLists.txt
  database.cpp
  database.h
  de_web_plugin.cpp
  device.cpp
  device_ddf_bundle.cpp
  device_ddf_bundle.h
  device_ddf_init.cpp
  device_descriptions.cpp
  device_descriptions.h
  devices/generic/items/attr_ddf_hash_item.json
  devices/generic/items/attr_ddf_policy_item.json
  resource.cpp
  resource.h
  rest_ddf.cpp
  rest_ddf.h
  rest_devices.cpp
  rest_devices.h
Labels: Enhancement

#7781 DDF for Tuya 4-gang switches (_TZ3000_a4xycprs, _TZ3000_u3nv1jwk)
  button_maps.json
  devices/tuya/_TZ3000_TS0044_4gang_remote_locked.json
Labels: Device Request

#7779 lidl/hg08673 / TS011F - Removed stray ";" that stopped consumption from working
  devices/lidl/hg08673.json
Labels: Fix

#7788 Log which modelid / manufacturer names lookup DDFs
  database.cpp
Labels: Enhancement

#7789 REST API GET DDF bundle descriptor, return file hash
  rest_ddf.cpp
Labels: Enhancement

#7790 REST API remove single DDF descriptor request
  rest_ddf.cpp
Labels: Enhancement

#7791 REST API improve DDF upload error reporting
  rest_api.h
  rest_ddf.cpp
Labels: API Extension

#7792 Improve bulk upload of DDF bundles and hotreload
  device_descriptions.cpp
  device_descriptions.h
  rest_devices.cpp
  ui/device_widget.cpp
Labels: Enhancement

#7796 DDF loader improve logging; load DDFs where mfname constant is unknown
  device_ddf_init.cpp
  device_descriptions.cpp
Labels: Enhancement

#7797 Fix Xiaomi curtain file extension
  devices/xiaomi/xiaomi_lumi.curtain.agl001.json
Labels: Fix
