Repository dresden-elektronik/deconz-rest-plugin, pull requests merged in 2024-02, with the labels that each got.

#7567 New `modelid` values for Hue smart button and Hue wall switch module
  devices/philips/rdm001_wall_switch_module.json
  devices/philips/rom001_smart_button.json
Labels: Device Request

#7565 Fix CentraLite Motion Sensor-A detection
  devices/centralite/motion_sensor-a.json
Labels: Fix

#7509 Fix battery spamming on Tuya smart button IH-663
  devices/tuya/_TZ3000_TS0041_1gang_bat.json
  devices/tuya/_TZ3000_ja5osu5g_smart_button.json
Labels: Fix

#7569 Remove legacy FLS-PP (version 1) color XY quirk
  bindings.cpp
  de_web_plugin.cpp
  de_web_plugin_private.h
  rest_groups.cpp
Labels: Enhancement

#7570 Optimize updatedLightNodeEndpoint()
  de_web_plugin.cpp
Labels: Enhancement

#7571 Skip more legacy code for DDF devices
  bindings.cpp
  de_web_plugin.cpp
Labels: Enhancement

#7574 Optimize idle timer and legacy device polling
  de_web_plugin.cpp
  device.cpp
  poll_manager.cpp
Labels: Enhancement

#7562 DDF for Philips Signe floor lamp (4080248P9)
  devices/philips/light_zb3_C.json
Labels: Device Request

#7576 Fix handling Hue Effects state attribute
  devices/philips/fc03_state.js
Labels: Confirmed Bug, Device Request

#7577 Fix MHCOZY 4-Channel SyntaxError: unterminated statement (_TZ3000_u3oupgdy)
  devices/mhcozy/ts0004.json
Labels: Confirmed Bug, Fix

#7578 Prevent heavy database writes during APS indications
  database.cpp
  database.h
  de_web_plugin.cpp
  device_ddf_init.cpp
  resource.cpp
  resource.h
Labels: Fix

#7581 Bug fix: Hue white ambiance wrong state
  devices/philips/fc03_state.js
  devices/philips/light_zll_white_ambiance.json
Labels: Confirmed Bug, Device Improvement

#7584 IKEA Vallhorn add missing bindings for light
  devices/ikea/vallhorn_wireless_motion_sensor.json
Labels: Enhancement

#7583 Corrected critical typo in _TZ3000_TS0041_1gang_bat.json
  devices/tuya/_TZ3000_TS0041_1gang_bat.json
Labels: Fix

#7580 Correct battery percentage of Danalock V3
  devices/danalock/danalock_v3.json
Labels: Fix

#7585 DDf add support for Moes Thermostat
  devices/tuya/_TZE200_ztvwu4nk_thermostat.json
Labels: Device Request

#7601 Relax polling of DDF devices without refresh.interval
  device_ddf_init.cpp
Labels: Enhancement

#7602 Fix unnecessary read requests for some Xiaomi devices
  devices/xiaomi/xiaomi_mfkzq12lm_t1_pro_cube.json
  devices/xiaomi/xiaomi_wrs-r02_h1_switch.json
Labels: Fix

#7604 Fix for IKEA Tradfri control outlet
  devices/ikea/tradfri_control_outlet.json
Labels: Fix

#7605 DDF support disable binding table requests
  device.cpp
  device.h
  device_descriptions.cpp
  device_descriptions.h
Labels: Enhancement

#7606 Add default refresh.interval of 5 secs to state/hue item
  devices/generic/items/state_hue_item.json
Labels: Enhancement

#7607 Improve ResourceItem::setValue() usage in Device class
  device.cpp
Labels: Enhancement

#7608 Fix OSRAM Classic A60 RGBW crash
  devices/osram/classic_a60_rgbw.json
Labels: Fix

#7609 DDF for OSRAM PAR16 50 TW (GU10)
  devices/osram/par16_50_tw.json
Labels: Device Request

#7610 DDF for LEDVANCE A60 FIL DIM T
  devices/osram/classic_a60_fil_dim_t.json
Labels: Device Request

#7611 More detailed ZGP logging, relax Friends of Hue switch detection
  de_web_plugin.cpp
Labels: Enhancement

#7613 Fix OSRAM Classic A60 W clear crash
  devices/osram/classic_a60_w_clear.json
Labels: Fix

#7616 Relax reporting interval of Sonfoff SNZB-02 multisensor
  devices/sonoff/snzb-02-multisensor.json
Labels: Enhancement

#7612 DDF variant for Tuya 2-channel switch (_TZ3000_lmlsduws)
  devices/tuya/_TZ3000_2channel_module.json
Labels: Device Request

#7625 Don't poll unsupported ZCL attributes more than once
  device.cpp
  resource.cpp
  resource.h
Labels: Enhancement

#7626 Fix StateChange write with invalid values on boot
  device_ddf_init.cpp
  state_change.cpp
Labels: Enhancement

#7627 Prevent store ResourceItem item of RDevice resource in APS indication
  de_web_plugin.cpp
Labels: Enhancement

#7618 Fix negative value for sensitivity for Aqara/Xiaomi vibration sensor
  devices/xiaomi/lumi_vibration_aq1.json
Labels: Fix

#7628 Refactor DuktapeJS memory management, use deCONZ library
  device_js/device_js_duktape.cpp
Labels: Enhancement

#7629 Remove old and unused QT Javascript engine code
  CMakeLists.txt
  device_js/device_js.cpp
  device_js/device_js_duktape.h
  device_js/device_js_wrappers.cpp
  device_js/device_js_wrappers.h
Labels: Enhancement

#7631 DDF clone for Tuya contact sensor (_TZ3000_zgrffiwg)
  devices/tuya/_TZ3000_2channel_module.json
  devices/tuya/_TZ3000_TS0203_door_sensor.json
Labels: Device Request

#7621 Fix consumption reporting for Lidl SilverCrest (_TZ3000_j1v25l17)
  devices/lidl/hg08673.json
Labels: Fix

#7634 JS add R.hasCluster(ep,clusterId [,side])
  device_js/device_js.h
  device_js/device_js_duktape.cpp
Labels: Enhancement

#7637 DEV refresh non sleeper endpoints and simple descriptors once per session
  device.cpp
  resource.cpp
  resource.h
Labels: Enhancement

#7638 Fix non stop reading of binding table for legacy devices
  bindings.cpp
  de_web_plugin.cpp
Labels: Enhancement

#7635 Philips Hue ZLL/ZB3 match DDF only for newer firmware
  devices/philips/light_zb3_C.json
  devices/philips/light_zb3_C_festavia.json
  devices/philips/light_zb3_C_gradient.json
  devices/philips/light_zb3_white.json
  devices/philips/light_zb3_white_ambiance.json
  devices/philips/light_zll_A.json
  devices/philips/light_zll_B.json
  devices/philips/light_zll_C.json
  devices/philips/light_zll_white_ambiance.json
Labels: Fix

#7642 Expose OTA file version for matchexpr
  database.cpp
  database.h
  de_otau.cpp
  de_web_plugin.cpp
  de_web_plugin_private.h
  device.cpp
  device.h
  device_access_fn.cpp
  device_ddf_init.cpp
  device_descriptions.cpp
  device_descriptions.h
  devices/generic/items/attr_appversion_item.json
  devices/generic/items/attr_otaversion_item.json
  resource.cpp
  resource.h
Labels: Enhancement
