Repository dresden-elektronik/deconz-rest-plugin, pull requests merged in 2024-06, with the labels that each got.

#7802 Refactor OpenSSL resolving
  crypto/mmohash.cpp
  crypto/random.cpp
  crypto/scrypt.cpp
  de_web.pro
  green_power.cpp
Labels: Fix

#7798 Add DDF for Wiser room thermostat CCTFR6400
  devices/wiser/room_thermostat_cctfr6400.json
Labels: Device Request

#7801 DDF for Drayton Wiser Radiator Thermostat iTRV
  devices/wiser/itrv_thermostat.json
Labels: Device Request

#7803 Fix DDF get descriptors request
  rest_ddf.cpp
Labels: Fix

#7809 BufString use U_ASSERT() instead of assert()
  utils/bufstring.h
Labels: Enhancement

#7808 DDF clone for Tuya Soil sensor (_TZE204_myd45weu)
  devices/tuya/_TZE200_myd45weu_soil_sensor.json
Labels: Device Request

#7813 Change DDF bundle file extension to .ddb
  device_descriptions.cpp
  rest_ddf.cpp
Labels: Enhancement

#7817 Fix crash on macOS
  device_descriptions.cpp
Labels: Fix
