Repository dresden-elektronik/deconz-rest-plugin, pull requests merged in 2024-11, with the labels that each got.

#8011 TRADFRI bulb E27 WW 806lm - intervals extended
  devices/ikea/tradfri_bulb_e27_ww_806lm.json
Labels: Enhancement

#8010 TRADFRI bulb E14 WS opal 600lm - intervals extended
  devices/ikea/tradfri_bulb_e14_ws_opal_600lm.json
Labels: Enhancement

#8009 TRADFRI bulb E27 WS opal 1000lm - intervals extended
  devices/ikea/tradfri_bulb_e27_ws_opal_1000lm.json
Labels: Enhancement

#8007 DDF for IKEA TRETAKT Smart plug (E2204)
  devices/ikea/tretakt_smart_plug.json
Labels: Device Request

#8004 DDF for Philips Hue Play Lightbar (LCT024)
  devices/philips/light_zll_C.json
Labels: Device Request

#8001 DDF for Philips HUE Play Lightbar (440400982842)
  devices/philips/light_zb3_C.json
Labels: Device Request

#7988 DDF clones for various model of Namrom Panel heater; data conversion correction
  devices/namron/5401395_heater.json
Labels: Device Request

#8002 DDF clones for Sonoff SNZB-04P
  devices/sonoff/snzb-04_open_close_sensor.json
Labels: Device Request

#7977 DDF for iluminize Multi 5 (4A)
  devices/iluminize/led_controller_multi_5.cct.json
  devices/iluminize/led_controller_multi_5.dim.json
  devices/iluminize/led_controller_multi_5.rgbcct.json
  devices/iluminize/led_controller_multi_5.rgbw.json
Labels: Device Request

#7970 Fix battery percentage for FireAngel Zigbee module
  devices/fireangel/0001_battery_voltage.js
Labels: Bug report, Fix

#7614 Add `config/setvalve` item to generic
  devices/generic/items/config_setvalve_item.json
Labels: Enhancement

#8017 Fix IKEA Somrig product type code
  devices/ikea/somrig_shortcut_button.json
Labels: Fix

#7963 Add Danfoss manufacturer specific commands to general.xml
  general.xml
Labels: Enhancement

#7964 Add Develco manufacturer specific commands to general.xml
  general.xml
Labels: Enhancement

#7961 ResourceItems for device firmware
  devices/dresden_elektronik/hive.json
  devices/dresden_elektronik/kobold.json
  devices/fireangel/co_alarm.json
  devices/fireangel/generic_alarm.json
  devices/fireangel/smoke_alarm.json
  devices/generic/items/cap_otau_file_version_item.json
  devices/generic/items/cap_otau_image_type_item.json
  devices/generic/items/cap_otau_manufacturer_code_item.json
  devices/icasa/ICZB-IW11D.json
  devices/icasa/ICZB-IW21D.json
  devices/icasa/ICZB-IW21SW.json
  devices/ikea/tradfri_driver_30w.json
  devices/innr/sp_240.json
  devices/philips/light_zb3_C.json
  devices/philips/light_zb3_C_festavia.json
  devices/philips/light_zb3_C_gradient.json
  devices/philips/light_zb3_white.json
  devices/philips/light_zb3_white_ambiance.json
  devices/philips/light_zll_A.json
  devices/philips/light_zll_B.json
  devices/philips/light_zll_C.json
  devices/philips/light_zll_white_ambiance.json
  devices/philips/lom007_smart_plug.json
  devices/philips/rdm001_wall_switch_module.json
  devices/philips/rdm002_tap_dial_switch.json
  devices/philips/rom001_smart_button.json
  devices/philips/rwl022_dimmer_switch.json
  devices/philips/rwl02_dimmer_switch.json
  devices/philips/sml001_motion_sensor.json
  devices/philips/sml002_motion_sensor.json
  devices/philips/sml003_motion_sensor.json
  devices/philips/sml004_motion_sensor.json
  devices/philips/soc001_contact_sensor.json
  resource.cpp
  resource.h
  rest_lights.cpp
  rest_sensors.cpp
Labels: Device Improvement, Enhancement

#8022 Ubisys Manufacturer-specific attributes in general.xml
  general.xml
Labels: Enhancement

#8043 Fix ResourceItems no longer processed when loading additional DDFs
  device_descriptions.cpp
Labels: Fix

#8044 Remove database save from API restartapp method
  rest_configuration.cpp
Labels: Enhancement
