Repository dresden-elektronik/deconz-rest-plugin, pull requests merged in 2025-04, with the labels that each got.

#8151 Expose button events from DDF
  device_descriptions.cpp
  device_descriptions.h
  rest_devices.cpp
Labels: Enhancement

#8154 Updated DDF for frient Intelligent Keypad (KEPZB-110)
  devices/frient/kepzb-110_keypad.json
Labels: Device Request, Device Improvement

#8158 Remove legacy code for Ikea remote control
  bindings.cpp
  de_web_plugin.cpp
  rest_sensors.cpp
Labels: Enhancement

#8084 Fix vendor, state and add cooling mode to Bosch room thermostat II 230V (BTH-RM230Z)
  devices/bosch/room_thermostat2_230V.json
Labels: Fix

#8123 DDF for LEDVANCE PLUG (COMPACT) EU EM T
  devices/ledvance/ledvance_plug_eu_em_t.json
Labels: Device Request

#8161 DDF for LEDVANCE Plug Z3
  devices/ledvance/plug_z3.json
Labels: Device Request

#8165 Fix StateChange requests while end device is sleeping
  device.cpp
Labels: Fix

#8159 DDF for Shelly 1 Mini Gen4
  devices/shelly/shelly_1_mini_gen4.json
Labels: Device Request

#8156 Removal of `config/temperature` from more Xiaomi devices (part 2)
  devices/xiaomi/lumi_curtain_acn002.json
  devices/xiaomi/xiaomi_lumi.relay.c2acn01.json
  devices/xiaomi/xiaomi_qbkg03lm_switch.json
  devices/xiaomi/xiaomi_qbkg04lm_switch.json
  devices/xiaomi/xiaomi_sp-euc01_smart_plug.json
  devices/xiaomi/xiaomi_wsdcgq01lm_temp_hum_sensor.json
  devices/xiaomi/xiaomi_zncz04lm_smart_plug.json
  devices/xiaomi/xiaomi_zncz04lm_smart_plug_v24.json
  devices/xiaomi/xiaomi_zncz12lm_smart_plug.json
Labels: Breaking Change

#8168 Disable ZCL Default Response APS ACKs by default
  aps_controller_wrapper.cpp
Labels: Fix

#7972 DDF for b-parasite plant sensor
  devices/b-parasite/0400_lightlevel.js
  devices/b-parasite/b-parasite.json
Labels: Device Request

#8170 Fix possibly wrong destination endpoints for ZCL commands
  de_web_plugin.cpp
  device.h
  device_access_fn.cpp
  resource.cpp
  resource.h
Labels: Fix

#8172 Fix don't query binding table for routers with no DDF bindings
  device.cpp
Labels: Fix

#8173 Fix loading Device reachable = true, set to false if older than 24h
  device_ddf_init.cpp
Labels: Fix

#8174 Fix to prevent poll attributes after startup if value timestamp is fresh enough
  device.cpp
Labels: Fix

#8175 Fix database not storing / fresh values of strings
  database.cpp
  device_ddf_init.cpp
Labels: Fix

#8176 Fix loading DDF devices from database which weren't fully setup
  database.cpp
Labels: Fix

#8178 Fix hot reload and events not emitted after joining a device
  device_descriptions.cpp
Labels: Fix

#8167 DDf adds support for Aeotec (Samjin) water leak sensor's
  devices/aeotec/water_sensor.json
  devices/bosch/bwa-1_water_sensor.json
Labels: Device Request

#8181 DDF for BlitzWolf BW-SHP-13 plug clone
  devices/blitzwolf/bw_shp13_smart_plug.json
Labels: Device Request

#8182 OSRAM/Centralite Motion Sensor-A fix wrong presence = false auto reset
  devices/centralite/motion_sensor-a.json
Labels: Fix

#8186 Fix CMake FetchContent_Populate() deprecated warnings
  CMakeLists.txt
  sqlite3/CMakeLists.txt
Labels: Fix

#8188 DDF for Xiaomi WXKG11LM 2018 switch
  button_maps.json
  de_web_plugin.cpp
  devices/xiaomi/xiaomi_wxkg11lm_2018_switch.json
Labels: Device Request

#8189 Fix ghost events for sensors
  de_web_plugin_private.h
  rest_sensors.cpp
Labels: Fix

#8192 DDF clone for temperature and humidity sensor (_TZE200_vs0skpuc)
  devices/tuya/_TZE200_TS0601_humidity_temp.json
Labels: Device Request

#8180 Add support for C401N user interface configuration
  general.xml
Labels: Enhancement

#8197 Fix Ikea scenes with on/off going wild
  resource.cpp
  resource.h
  rest_groups.cpp
Labels: Fix
