Repository dresden-elektronik/deconz-rest-plugin, pull requests merged in 2025-05, with the labels that each got.

#8202 Ensure lights and sensors always have valid Etag
  rest_lights.cpp
  rest_sensors.cpp
Labels: Fix

#8213 Fix ResourceItem set (UTC) timestamps from string
  resource.cpp
Labels: Fix

#8214 Make Device creation time available
  database.cpp
  database.h
  de_web_plugin.cpp
  device.cpp
  device.h
Labels: Enhancement

#8215 Fix attr/lastannounced and attr/lastseen sometimes being null
  rest_lights.cpp
  rest_sensors.cpp
Labels: Fix

#8216 Fix don't expose internal attr/zonetype to REST-API
  device.cpp
Labels: Fix

#8218 Improve ZGP device representation
  database.cpp
  de_web_plugin.cpp
  device.cpp
Labels: Enhancement

#8220 Fix don't expose Configuration tool (coordinator) lastannounced
  device.cpp
  light_node.cpp
Labels: Fix

#8221 Fix missing lights and groups Websocket deleted events
  rest_groups.cpp
  rest_lights.cpp
Labels: Fix

#8207 DDF for Shelly 1 gen4
  devices/shelly/shelly_1_gen4.json
Labels: Device Request

#8205 DDF for Shelly 1PM gen4
  devices/shelly/shelly_1pm_gen4.json
Labels: Device Request

#8203 DDF for Ubisys Router R0
  devices/ubisys/r0_5501.json
Labels: Device Request

#8201 DDF for Shelly 1PM mini gen4
  devices/shelly/shelly_1pm_mini_gen4.json
Labels: Device Request

#8196 DDF clone for Tuya door/window sensor (_TZ3000_bpkijo14)
  devices/tuya/_TZ3000_TS0203_door_sensor.json
Labels: Device Request

#8222 Fix don't expose null values from Device for sensors and lights
  rest_lights.cpp
  rest_sensors.cpp
Labels: Fix

#8199 Expose NWK address as hex value through REST API
  resource.cpp
  resource.h
  rest_lights.cpp
  rest_sensors.cpp
Labels: Enhancement

#8230 Fix /devices endpoint not having UTC timestamps for "value"
  rest_devices.cpp
Labels: Fix

#8226 Enable status reporting for Parkside Smart Watering Timer (_TZE200_htnnfasr)
  devices/lidl/hg06875.json
Labels: Enhancement

#8228 Update general.xml file to use more data from LiXee device
  general.xml
Labels: Enhancement

#8231 DDF clone for Tuya smoke detector (_TZE284_rccxox8p)
  devices/tuya/_TZE200_TS0601_smoke_detector.json
Labels: Device Request

#8235 DDF clone for Tuya temperature/humidity sensor (_TZE284_wtikaxzs)
  devices/tuya/_TZE200_TS0601_humidity_temp.json
Labels: Device Request
