Repository dresden-elektronik/deconz-rest-plugin, pull requests merged in 2025-08, with the labels that each got.

#8288 Fix creation of invalid Unicast Bindings
  device_descriptions.h
Labels: Fix

#8293 Fix QDateTime::toTime_t() missing in Qt6
  rest_configuration.cpp
Labels: Fix

#8295 Support build with Qt6 (alpha)
  CMakeLists.txt
  rest_rules.cpp
  rule.cpp
  ui/ddf_editor.cpp
  ui/ddf_itemeditor.cpp
Labels: Enhancement

#8289 DDF for Namron Zigbee Stove Guard 140279X
  devices/namron/140279X_stove_guard.json
  general.xml
Labels: Device Request

#8297 Fix state/reachable and config/reachable not stored in database
  de_web_plugin.cpp
  device.cpp
  zdp/zdp_handlers.cpp
Labels: Fix

#8305 DDF for Tuya Motion Sensor TS0601 (_TZE200_bh3n6gk8/_TZE200_1ibpyhdc)
  devices/tuya/_TZE200_bh3n6gk8_motion_sensor.json
Labels: Device Request
